

-- INSERT VALUE FOR DETAIL COURSE TABLE
insert into DETAIL_COURSE values('co01_01','Social Network Analysis with Lada Adamic','1:58','', 'co01', 0, '', 0)
insert into DETAIL_COURSE values('co01_02','Network Analysis in Systems Biology Coursera Promo by Professor Avi Maayan','1:52','', 'co01', 0, '', 0)
insert into DETAIL_COURSE values('co01_03','Machine Learning: About the class','1:59','','co01',0,'',0)
insert into DETAIL_COURSE values('co01_04','Probabilistic Graphical Models with Daphne Koller','3:11','','co01',0,'',0)
insert into DETAIL_COURSE values('co02_01','Introduction to Logic with Michael Genesereth','2:16','','co02',0,'',0)
insert into DETAIL_COURSE values('co02_02','Scientific Computing with J. Nathan Kutz','2:03','','co02',0,'',0)
insert into DETAIL_COURSE values('co02_03','Initiation a la theorie des distributions with Francois Golse and Yvan Martel','2:08','','co02',0,'',0)
insert into DETAIL_COURSE values('co03_01','Cardiac Arrest, Hypothermia, and Resuscitation Science with Benjamin Abella, MD MPhil','2:37','','co03',0,'',0)
insert into DETAIL_COURSE values('co03_02','Principles of Public Health with Zuzana Bic','2:32','','co03',0,'',0)
insert into DETAIL_COURSE values('co03_03','Canine Theriogenology for Dog Enthusiasts with Margaret V. Root','1:22','','co03',0,'',0)
insert into DETAIL_COURSE values('co03_04','Basic Behavioral Neurology with Roy Hamilton, MD','2:34','','co03',0,'',0)
insert into DETAIL_COURSE values('co03_05','Fundamentals of Pharmacology with Emma Meagher','2:25','','co03',0,'',0)
insert into DETAIL_COURSE values('co04_01','IBM Blockchain Foundation for Developers - The business backdrop by IBM #1','2:50','','co04',0,'',0)
insert into DETAIL_COURSE values('co04_02','IBM Blockchain Foundation for Developers - The Problem Area by IBM #2','4:08','','co04',0,'',0)
insert into DETAIL_COURSE values('co04_03','IBM Blockchain Foundation for Developers - Why blockchain is relevant for business by IBM #3','2:33','','co04',0,'',0)
insert into DETAIL_COURSE values('co05_01','Introduction to Programming for Musicians and Digital Artists with Ajay Kapur','1:24','','co05',0,'',0)
insert into DETAIL_COURSE values('co05_02','Algorithms Part 2 with Robert Sedgewick and Kevin Wayne','1:22','','co05',0,'',0)
insert into DETAIL_COURSE values('co05_03','Principles of Reactive Programming with Martin Odersky, Erik Meijer, and Roland','1:59','','co05',0,'',0)
insert into DETAIL_COURSE values('co05_04','Compilers with Alex Aiken','1:33','','co05',0,'',0)
insert into DETAIL_COURSE values('co05_05','Algorithms Part 1 with Robert Sedgewick and Kevin Wayne','1:17','','co05',0,'',0)
insert into DETAIL_COURSE values('co05_06','Computer Science 101','1:10','','co05',0,'',0)
insert into DETAIL_COURSE values('co06_01','Gain skills to succeed as a data science professional','1:20','','co06',0,'',0)
insert into DETAIL_COURSE values('co06_02','Earn a Professional Certificate and launch a career as a data professional','1:30','','co06',0,'',0)
insert into DETAIL_COURSE values('co06_03','Advance your career in Data Science with the IBM Data Science Professional Certificate','1:00','','co06',0,'',0)
insert into DETAIL_COURSE values('co06_04','Advance your career in Data Science with the IBM Data Science Professional Certificate','0:32','','co06',0,'',0)
insert into DETAIL_COURSE values('co07_01','Meet the Professor - Introduction to Data Analysis Using Excel by Rice University #1','1:35','','co07',0,'',0)
insert into DETAIL_COURSE values('co07_02','Reading Data into Excel - Introduction to Data Analysis Using Excel by Rice University #2','7:18','','co07',0,'',0)
insert into DETAIL_COURSE values('co08_01','Welcome to Data Science Methodology by IBM #1','3:53','','co08',0,'',0)
insert into DETAIL_COURSE values('co08_02','Business Understanding - Data Science Methodology by IBM #2','5:02','','co08',0,'',0)
insert into DETAIL_COURSE values('co08_03','Analytics Approach - Data Science Methodology by IBM #3','3:24','','co08',0,'',0)
insert into DETAIL_COURSE values('co09_01','Welcome to Big Data and Machine Learning Fundamentals from Google Cloud #1','0:55','','co09',0,'',0)
insert into DETAIL_COURSE values('co09_02','GCP Course Overview & Agenda - Google Cloud Platform Big Data and Machine Learning Fundamentals #2','5:46','','co09',0,'',0)
insert into DETAIL_COURSE values('co09_03','Getting Started with Qwiklabs - Google Cloud Platform Big Data and Machine Learning Fundamentals #3','2:10','','co09',0,'',0)
insert into DETAIL_COURSE values('co09_04','Meet Your Instructor - Google Cloud Platform Big Data and Machine Learning Fundamentals #4','3:55','','co09',0,'',0)
insert into DETAIL_COURSE values('co10_01','François Lignon and Fabienne Diouf - MSIE students from HEC Paris share their experience','2:40','','co10',0,'',0)
insert into DETAIL_COURSE values('co10_02','Till Bärnighausen - MSIE student from HEC Paris share their experience','2:15','','co10',0,'',0)
insert into DETAIL_COURSE values('co10_03','Dennis Zaidi and Ikenna Njubigbo - MSIE students from HEC Paris share their experience','2:21','','co10',0,'',0)
insert into DETAIL_COURSE values('co11_01','Why SQL? - Databases and SQL for Data Science by IBM #1','2:17','','co11',0,'',0)
insert into DETAIL_COURSE values('co11_02','Introduction to Databases - Databases and SQL for Data Science by IBM #2','4:23','','co11',0,'',0)
insert into DETAIL_COURSE values('co11_03','How to create a Database instance on Cloud? - Databases and SQL for Data Science #3','4:11','','co11',0,'',0)
insert into DETAIL_COURSE values('co12_01','CREATE Table Statement - Databases and SQL for Data Science by IBM #4','2:51','','co12',0,'',0)
insert into DETAIL_COURSE values('co12_02','SELECT Statement - Databases and SQL for Data Science by IBM #5','3:36','','co12',0,'',0)
insert into DETAIL_COURSE values('co12_03','INSERT Statement - Databases and SQL for Data Science by IBM #6','2:36','','co12',0,'',0)
insert into DETAIL_COURSE values('co13_01','UPDATE and DELETE Statements - Databases and SQL for Data Science by IBM #7','3:12','','co13',0,'',0)
insert into DETAIL_COURSE values('co13_02','Information and Data Models - Databases and SQL for Data Science by IBM #8','4:52','','co13',0,'',0)
insert into DETAIL_COURSE values('co13_03','Types of Relationships - Databases and SQL for Data Science by IBM #9','3:13','','co13',0,'',0)
insert into DETAIL_COURSE values('co14_01','Mapping Entities to Tables - Databases and SQL for Data Science by IBM #10','1:48','','co14',0,'',0)
insert into DETAIL_COURSE values('co14_02','Relational Model Concepts - Databases and SQL for Data Science by IBM #11','2:58','','co14',0,'',0)
insert into DETAIL_COURSE values('co15_01','Course Introduction - Living with Dementia by JHU #1','4:00','','co15',0,'',0)
insert into DETAIL_COURSE values('co15_02','Module Introduction - Living with Dementia by JHU #2','0:46','','co15',0,'',0)
insert into DETAIL_COURSE values('co15_03','Alzheimer’s Disease: A Brief History - Living with Dementia by JHU #3','7:04','','co15',0,'',0)
insert into DETAIL_COURSE values('co16_01','Global Impact of Dementia - Living with Dementia by JHU','20:44','','co16',0,'',0)
insert into DETAIL_COURSE values('co17_01','Introduction to Machine Learning on GCP - How Google does Machine Learning from Google Cloud #1','1:56','','co17',0,'',0)
insert into DETAIL_COURSE values('co17_02','Specialization Agenda - How Google does Machine Learning from Google Cloud #2','5:35','','co17',0,'',0)
insert into DETAIL_COURSE values('co17_03','Why Google? - How Google does Machine Learning from Google Cloud #3','1:39','','co17',0,'',0)
insert into DETAIL_COURSE values('co17_04','Why Google Cloud? - How Google does Machine Learning from Google Cloud #4','2:10','','co17',0,'',0)
insert into DETAIL_COURSE values('co18_01','Welcome to the Course - Introduction to the Biology of Cancer by Johns Hopkins University','3:23','','co18',0,'',0)
insert into DETAIL_COURSE values('co18_02','Incidence & Etiology Overview - Introduction to the Biology of Cancer by Johns Hopkins University','0:39','','co18',0,'',0)
insert into DETAIL_COURSE values('co18_03','Cancer Incidence - Introduction to the Biology of Cancer by Johns Hopkins University','4:08','','co18',0,'',0)
insert into DETAIL_COURSE values('co19_01','Incidence and Etiology of Cancer - Introduction to the Biology of Cancer','10:26','','co19',0,'',0)
insert into DETAIL_COURSE values('co20_01','Caring About Others - Moralities of Everyday Life by Yale University','10:41','','co20',0,'',0)
insert into DETAIL_COURSE values('co21_01','About Specialization - End-to-End Machine Learning with Tensorflow from Google Cloud #1','1:37','','co21',0,'',0)
insert into DETAIL_COURSE values('co21_02','Introduction to End-to-End Machine Learning with Tensorflow from Google Cloud #2','3:07','','co21',0,'',0)
insert into DETAIL_COURSE values('co21_03','Effective ML - End-to-End Machine Learning with Tensorflow from Google Cloud #3','5:38','','co21',0,'',0)
insert into DETAIL_COURSE values('co21_04','Fully managed ML - End-to-End Machine Learning with Tensorflow from Google Cloud #4','5:51','','co21',0,'',0)
insert into DETAIL_COURSE values('co22_01','Exploring the dataset - End-to-End Machine Learning with TensorFlow on GCP from Google Cloud #5','5:36','','co22',0,'',0)
insert into DETAIL_COURSE values('co22_02','BigQuery - End-to-End Machine Learning with TensorFlow on GCP from Google Cloud #6','3:46','','co22',0,'',0)
insert into DETAIL_COURSE values('co22_03','Datalab - End-to-End Machine Learning with TensorFlow on GCP from Google Cloud #7','3:03','','co22',0,'',0)
insert into DETAIL_COURSE values('co23_01','Lab Demo - Explore & Visualize Datasets - Machine Learning with Tensorflow from Google Cloud','10:33','','co23',0,'',0)
insert into DETAIL_COURSE values('co24_01','Introduction to Excel Skills for Business: Essentials by Macquarie University #1','2:50','','co24',0,'',0)
insert into DETAIL_COURSE values('co24_02','Excel Discussion - Excel Skills for Business: Essentials by Macquarie University #2','3:39','','co24',0,'',0)
insert into DETAIL_COURSE values('co24_03','Taking Charge of Excel - Excel Skills for Business: Essentials by Macquarie University #3','7:07','','co24',0,'',0)
insert into DETAIL_COURSE values('co24_04','Navigating and Selecting in Excel - Excel Skills for Business: Essentials by Macquarie University #4','5:36','','co24',0,'',0)
insert into DETAIL_COURSE values('co25_01','View Options - Excel Skills for Business: Essentials by Macquarie University #5','5:29','','co25',0,'',0)
insert into DETAIL_COURSE values('co25_02','Data Entry, Editing & Deleting - Excel Skills for Business: Essentials by Macquarie University #6','6:46','','co25',0,'',0)
insert into DETAIL_COURSE values('co25_03','Fill Handle - Excel Skills for Business: Essentials by Macquarie University #7','5:30','','co25',0,'',0)
insert into DETAIL_COURSE values('co25_01','Week 1 Wrap-Up - Excel Skills for Business: Essentials by Macquarie University #8','1:41','','co26',0,'',0)
insert into DETAIL_COURSE values('co25_02','Copying and Pasting in Excel - Excel Skills for Business: Essentials by Macquarie University #9','5:01','','co26',0,'',0)
insert into DETAIL_COURSE values('co25_03','Excel Templates - Excel Skills for Business: Essentials by Macquarie University #10','2:29','','co26',0,'',0)
